name: rhessi20-tutorial
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - rise
    - astroquery
    - pyyaml
    - sunpy>=3.0.1
    - git+https://github.com/sunpy/radiospectra
    - git+https://github.com/samaloney/stixpy.git
    - requests